const express = require('express');
const app = express();

// Определение ваших данных как объекта JavaScript
const responses = {
    "hello": "Hi! How are you?",
    "weather": "I can't check the weather, but I hope it's nice!",
    "thank you": "You're welcome! Always happy to help.",
    "goodbye": "Goodbye! Hope to see you again soon!",
    "help": "Sure, how can I assist you today?",
    "time": "I'm not sure what time it is, but I hope you're having a great day!",
    "food": "I love talking about food! What's your favorite dish?",
    "game": "Games are fun! What's your favorite?",
    "music": "Music is a great way to relax. Do you have a favorite song?",
    "book": "Reading is wonderful! Any books you can recommend?",
    "movie": "Movies are a great form of entertainment. What's your favorite?",
    "friend": "Friends are important! How are your friends doing?",
    "happy": "It's great to hear you're happy!",
    "sad": "I'm sorry to hear that. I'm here to chat if you need.",
    "bored": "Let's find something fun to talk about!",
    "excited": "That's awesome! What's got you excited?",
    "travel": "Traveling can be an amazing experience. Where would you like to go?",
    "school": "School is an important part of life. Are you enjoying it?",
    "work": "Work can be challenging but rewarding. How's it going for you?",
    "hobby": "Hobbies are a great way to relax. What do you enjoy doing?",
    "sport": "Sports are exciting! Do you play any?",
    "art": "Art is a wonderful form of expression. Do you create art?",
    "history": "History is fascinating! Any particular period you like?",
    "science": "Science helps us understand the world. What's your favorite branch?",
    "technology": "Technology is ever-changing. Are you a tech enthusiast?",
    "computer": "Computers are incredible tools. Do you like programming?",
    "internet": "The internet connects us all. What's your favorite website?",
    "language": "Learning languages can be fun. Do you speak any others?",
    "culture": "Culture adds color to our lives. What's interesting to you?",
    "holiday": "Holidays are a time to relax. Do you have a favorite one?",
    "dream": "Dreams can be adventurous. Do you remember yours?",
    "pet": "Pets are wonderful companions. Do you have any?",
    "family": "Family is important. How's your family doing?",
    "nature": "Nature is beautiful. Do you like spending time outdoors?",
    "city": "Cities are full of life. Do you live in a big city or a small town?",
    "country": "Countries have unique cultures. Where are you from?",
    "future": "The future holds many possibilities. What are your hopes?",
    "past": "The past shapes us. Any memorable moments?",
    "memory": "Memories are treasures. Do you have a favorite one?",
    "plan": "Planning ahead is smart. What's your next big plan?",
    "goal": "Goals keep us motivated. What's yours?",
    "success": "Success means different things to different people. What's your take?",
    "fear": "Facing fears can be tough. Do you have any?",
    "challenge": "Challenges help us grow. Any recent challenges?",
    "adventure": "Adventures are thrilling. What's your next one?",
    "happiness": "Happiness is a wonderful feeling. What makes you happy?",
    "love": "Love is powerful. Who do you love?",
    "relationship": "Relationships take work. How's yours?",
    "community": "Communities bring people together. Are you part of one?",
    "volunteer": "Volunteering is rewarding. Have you tried it?",
    "charity": "Charity helps those in need. Any causes you support?",
    "environment": "Protecting the environment is crucial. Do you recycle?",
    "health": "Health is wealth. How do you stay healthy?",
    "exercise": "Exercise keeps us fit. Do you have a routine?",
    "diet": "Diet affects well-being. Are you following any?",
    "recipe": "Cooking is an art. Do you have a favorite recipe?",
    "drink": "Staying hydrated is important. What's your favorite drink?",
    "coffee": "Coffee is energizing. How do you take yours?",
    "tea": "Tea is calming. Do you have a favorite type?",
    "vegetable": "Vegetables are healthy. Do you have a favorite?",
    "fruit": "Fruits are delicious. What's your favorite?",
    "dessert": "Desserts are a treat. Do you have a sweet tooth?",
    "chocolate": "Chocolate is irresistible. Do you prefer dark or milk?",
    "party": "Parties are fun! When's the next one you're attending?",
    "celebrate": "Celebrations mark special occasions. What's the latest you celebrated?",
    "gift": "Gifts show you care. Have you given or received any lately?",
    "shopping": "Shopping can be therapeutic. Do you enjoy it?",
    "fashion": "Fashion is ever-evolving. Do you follow trends?",
    "style": "Style is personal. How would you describe yours?",
    "clothes": "Clothes are a form of self-expression. Do you have a favorite outfit?",
    "shoes": "Shoes complete an outfit. Do you prefer comfort or style?",
    "accessory": "Accessories add flair. Do you wear any?",
    "jewelry": "Jewelry can be sentimental. Do you have a favorite piece?",
    "watch": "Watches are both practical and stylish. Do you wear one?",
    "car": "Cars offer freedom. Do you have a dream car?",
    "travel": "Travel broadens the mind. What's your next destination?",
    "flight": "Flying is an adventure. Do you enjoy air travel?",
    "hotel": "Hotels offer comfort away from home. Any favorites?",
    "beach": "Beaches are relaxing. Do you prefer the ocean or the pool?",
    "mountain": "Mountains are majestic. Do you hike or ski?",
    "forest": "Forests are serene. Do you enjoy nature walks?",
    "desert": "Deserts have unique beauty. Have you visited one?",
    "island": "Islands offer escape. Do you have a favorite?",
    "city": "Cities are vibrant. Which ones have you visited?",
    "village": "Villages are charming. Do you prefer quiet places?",
    "roadtrip": "Road trips offer freedom. Have you been on one recently?",
    "cruise": "Cruises are luxurious. Would you like to go on one?",
    "train": "Train journeys can be scenic. Have you traveled by train?",
    "bus": "Buses are convenient. Do you use public transport?",
    "bicycle": "Cycling is eco-friendly. Do you ride a bike?",
    "hike": "Hiking is refreshing. Do you enjoy it?",
    "swim": "Swimming is a great workout. Are you a strong swimmer?",
    "run": "Running keeps you fit. Do you run regularly?",
    "yoga": "Yoga calms the mind. Have you tried it?",
    "dance": "Dancing is joyful. Do you dance?",
    "sing": "Singing is uplifting. Do you have a favorite song to sing?",
    "play": "Playing is fun. What's your favorite game?",
    "relax": "Relaxation is vital. How do you unwind?",
    "stress": "Stress can be managed. How do you cope with it?",
    "sleep": "Sleep is essential. Do you get enough rest?",
    "goal": "Goals guide us. What's your current goal?",
    "learn": "Learning keeps us growing. What are you learning now?",
    "teach": "Teaching can be rewarding. Have you taught anything?",
    "create": "Creativity is limitless. What do you create?",
    "build": "Building is satisfying. Have you built something recently?",
    "design": "Design shapes our world. Are you into design?"
};

// Настройка маршрута для предоставления данных
app.get('/responses', (req, res) => {
  res.json(responses);
});

// Запуск сервера
const listener = app.listen(process.env.PORT || 3000, () => {
  console.log(`Your app is listening on port ${listener.address().port}`);
});
